version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - xcord-network

  backend:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=xcord_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - xcord-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=xcord_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - xcord-network

volumes:
  postgres_data:

networks:
  xcord-network:
    driver: bridge
