global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:5000']

  - job_name: 'voice-service'
    static_configs:
      - targets: ['voice-service:6000']

  - job_name: 'server-management-service'
    static_configs:
      - targets: ['server-management-service:7000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']